# Generated by Django 5.0.4 on 2024-04-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_blogs_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='../hello.jpg', upload_to='media/blogs'),
        ),
    ]
