# Generated by Django 5.0.4 on 2024-05-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post_type',
            field=models.CharField(blank=True, choices=[('Advice', 'Advice'), ('Experience', 'Experience'), ('Question', 'Question')], default='Question', max_length=50, null=True),
        ),
    ]
