# Generated by Django 5.0.4 on 2024-05-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_blog_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_type',
            field=models.CharField(choices=[('tips', 'Caregiving Tips and Best Practices'), ('health', 'Health and Wellness Articles'), ('stories', 'User Stories and Experiences')], default='tips', max_length=10),
        ),
    ]
