# Generated by Django 5.0.4 on 2024-05-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_remove_post_comments_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
    ]
