# Generated by Django 5.0.4 on 2024-05-09 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='is_recurring_field',
            new_name='is_recurring',
        ),
    ]
