# Generated by Django 5.0.4 on 2024-05-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_apartment_building_name_booking_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='city',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='apartment_building_name',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='hno',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='street',
        ),
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
